# Generated by Django 4.1.7 on 2023-03-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id_tinkoff',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ID платежной системы'),
        ),
    ]
