# Generated by Django 4.1.7 on 2023-03-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_course_owner_course_lesson_owner_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(default=0, verbose_name='Стоимость курса'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.FloatField(default=0, verbose_name='Стоимость урока'),
        ),
    ]
