# Generated by Django 4.1.7 on 2023-03-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_course_price_lesson_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(default=100, verbose_name='Стоимость курса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='price',
            field=models.FloatField(default=100, verbose_name='Стоимость урока'),
        ),
    ]
