# Generated by Django 4.1.7 on 2023-03-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_course_price_alter_lesson_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время обновления'),
        ),
    ]
